### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by brunoqs** [keitaroinc/ckanext-cas#1]
When i log in cas, the ckan returns ssl error, how can i disable ssl or validate the key in ckan?

I had the following error:
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

**Comment by brunoqs** [comment]
The solution:
Go to ckanext-cas controller.py and in the function: def cas_callback (self, ** kwargs):
change q = rq.get (cas_plugin.SERVICE_VALIDATION_URL, params = {cas_plugin.TICKET_KEY: ticket, cas_plugin.SERVICE_KEY: cas_plugin.CAS_APP_URL + '/ cas / callback'}) 
for 
q = rq.get (cas_plugin.SERVICE_VALIDATION_URL, params = {cas_plugin.TICKET_KEY: ticket, cas_plugin.SERVICE_KEY: cas_plugin.CAS_APP_URL + '/ cas / callback'}, verify = False)

**Comment by ljupchokotev** [comment]
I have added a new config variable `ckanext.cas.verify_certificate` which can be set to `true` or `false` to enable or disable certificate verification. 

I am not getting the `XMLSyntaxError: Opening and ending tag mismatch: meta line 3 and head, line 4, column 10 (line 4)` error when I set `verify=False`. 

Can you re-test?

**Comment by brunoqs** [comment]
When I get back to work I will test and post the results here. Just one more question is it necessary to have django installed for ckanext-cas to work?

**Comment by ljupchokotev** [comment]
We have developed ckanext-cas against django-mama-cas and its implementation of the CAS protocol. I haven't tested to see if it works with any other CAS provider, I believe that it should work with any other providers that closely follow the CAS protocol.

**Comment by mbocevski** [comment]
@brunoqs if you are integrating it with another CAS service, please let us know which one and whether it works fine.
