### ISSUE TITLE
Table name error in the setup ? 

### ISSUE THREAD

**Issue by gsueur** [keitaroinc/ckanext-cas#2]
Hi,

I think there is a tiny bug in the setup of db.py 
When the existence of the index is checked, and it doesn't exist, it is then created :
index_names = [index['name'] for index in inspector.get_indexes("ckanext_cas_login")]
        if not "ckanext_cas_login_ticket_id_idx" in index_names:
            log.debug('Creating index for ckanext_cas_login')
            Index("ckanext_cas_login_ticket_id_idx", cas_table.c.ckanext_cas_login_ticket_id).create()

but isn't the column name wrong here (ckanext_cas_login_ticket_id) ? the column itself is named ticket_id. and actually, the script does fail when the setup is run. 
Best regards
Guillaume

**Comment by polarp** [comment]
Hi @gsueur,

You are correct, there is a bug when setting up the index but I just pushed a fix (488844bdc6a594e0707eb31fbf6ed618f6a5f731).
Can you test it and let me know if everything is fine so I can close the issue?

BR,
Petar

**Comment by gsueur** [comment]
That looks good, sorry for the delay. 
Thanks
