### ISSUE TITLE
Notification on login

### ISSUE THREAD

**Issue by gsueur** [keitaroinc/ckanext-cas#3]
Hi,

It's more a question than a real issue, but there is a annoying side effect of the user update on CAS login. Each time the user logs in every follower of its organization gets a notification about "User has updated his profile". 
Is there a way to avoid sending a notification when you update the user ? 

Thanks
Guillaume

**Comment by ljupchokotev** [comment]
Hi Guillaume,

I have changed the code to check if a user update is needed. The user will get updated in CKAN only if you have updated his information in CAS.

You can pull the latest version from the master branch and try it out.

- Ljupcho

**Comment by gsueur** [comment]
That you very much Ljupcho ! That looks smart et fits perfectly our needs !
